aliases: []
description: The ability to monitor and manage the performance of software applications.
id: capability:application-performance-monitoring
name: Application Performance Monitoring
type: Capability
